model_loading_config:
  model_id: meta-llama/Llama-3.1-8B-Instruct

# Not specify the accelerator type to do more coverage
# accelerator_type: A10G

engine_kwargs:
  max_model_len: 8192
  tensor_parallel_size: 2
